events {
    worker_connections 1024;               # Максимум одновременных подключений
}

http {
    include /etc/nginx/mime.types;         # Типы файлов: css, js, картинки и т.д.
    default_type application/octet-stream; # Если тип не определён — отдаём как фай

    server {
        listen 80;                         # Порт HTTP (стандартный для сайтов)
        server_name _;                     # "_" = принимать запросы на любой IP или домен

        location /static/ {                # Если URL начинается с /static/
            alias /app/staticfiles/;       # Бери файлы из этой папки внутри контейнера
        }                                  # /app/staticfiles/ — туда Django собрал всю статику


        location / {                       # Для всех URL, кроме /static/
            proxy_pass http://backend:8000;     # Отправляем запрос в контейнер "backend" на порт 8000
                                                 # "backend" — имя сервиса в docker-compose.yml

            # Передаём заголовки, чтобы Django знал реальный IP посетителя
            proxy_set_header Host $host;                           # Домен из запроса
            proxy_set_header X-Real-IP $remote_addr;               # Реальный IP посетителя
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;   # Вся цепочка IP
            proxy_set_header X-Forwarded-Proto $scheme;            # HTTP или HTTPS
        }
    }
}
