# Generated by Django 6.0.4 on 2026-05-02 19:27

import django.db.models.deletion
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text='Где выполнять привычку (например, "Парк", "Дом", "Офис")',
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Во сколько выполнять привычку (например, 08:00)",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text='Что именно делать (например, "Пробежка 3 км")',
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если это ПРИЯТНАЯ привычка (награда за полезную). У приятной привычки НЕ может быть вознаграждения или связанной привычки.",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        default=1,
                        help_text="Через сколько дней повторять привычку. От 1 (каждый день) до 7 (раз в неделю)",
                        validators=[habits.validators.validate_period],
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text='Чем наградить себя за выполнение (например, "Съесть десерт"). Нельзя заполнить одновременно со Связанной привычкой.',
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Сколько секунд выполнять привычку. Максимум 120 секунд (2 минуты)",
                        validators=[habits.validators.validate_duration],
                        verbose_name="Время выполнения (секунды)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если отмечено — другие пользователи увидят эту привычку в общем списке",
                        verbose_name="Публичная",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "last_sent",
                    models.DateField(
                        blank=True,
                        help_text="Когда в последний раз отправляли напоминание",
                        null=True,
                        verbose_name="Дата последней отправки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка-награда за выполнение этой полезной. Нельзя заполнить одновременно с Вознаграждением.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="useful_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
